name: cos-lma-comparator
base: core22
version: '0.1'
summary: Tool to compare nrpe data between LMA and COS
description: |
  This tool aims to provide a mean to compare alert presence and completeness
  between the old LMA stack and the newer COS stack.
license: AGPL-3.0

grade: devel
confinement: strict

parts:
  clc:
    plugin: python
    source: .
    stage-snaps:
      - juju/3.1/beta

apps:
  clc:
    command: bin/clc
    plugs:
      - network
      - network-bind
      - juju-client-observe
      - dot-local-share-juju

plugs:
  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju
